version: '3'
services: 
  archivos-pruebas:
    image: pos-archivos
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
        - 8083:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - TZ=America/Tegucigalpa
    volumes:
        - /data/api-archivos:/media/archivos